### ISSUE TITLE
"No tables found" in PostgreSQL connection

### ISSUE THREAD

**Issue by Jagrutiti** [d4software/QueryTree#137]
Hi

I have installed QueryTree using Docker and connected it to a database.

I saw two already existing issues but did not find the solution. 

The database I have connected to has multiple schemas, each schema has multiple tables. There are also views and procedures in the database. 

![image](https://user-images.githubusercontent.com/28809492/181206963-9dbc8519-5d33-447f-828e-b15837f779bd.png)

**Comment by mdduarte1970** [comment]
Hello,

I also have the same problem with PostgreSQL, and it started happening to me about 5 days ago without having changed anything in the configurations. Anyone having the same problem?

**Comment by mdduarte1970** [comment]
help wanted

**Comment by Jagrutiti** [comment]
I haven't found a solution yet. Google search told me it is because of the table structure or something. I do not know what kind of structure it wants.

**Comment by Recodify** [comment]
Having the same problem with mysql

**Comment by Recodify** [comment]
Ok the problem with mysql is that the current version of the mysql package does not suport utf8mb3. This issue is then made less obvious by a lack of logging. This draft PR is addresses both of these issues by adding logging and bumping the version of MySql.Data

This is not a production ready PR, it's missing tests, but thought it might be useful to someone as a reference.

**Comment by d4nt** [comment]
Following the recent update to .net 6, I've been testing with MySQL and Postgres, in both cases it can find the tables ok. Not seeing any tables is probably an indicate that there is something wrong with the connection settings. Remember to use the "Test Connection" button. We've also added some extra logging now which may help if you encounter this issue.
