### ISSUE TITLE
postgresql db connection issue

### ISSUE THREAD

**Issue by allang1** [d4software/QueryTree#74]
I get the following error on my digitalocean server 
no pg_hba.conf entry for host "129.39.78.51", user "tesr", database "test", SSL off

**Comment by PandelisZ** [comment]
You'll probably want to check your postgresql conf

https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host

**Comment by joshuakarjala** [comment]
Why is there no flag to enable ssl connection? I don't want to lessen security on my postgres server

**Comment by d4nt** [comment]
According to <https://www.postgresql.org/docs/current/libpq-ssl.html> the default SSL mode for PostgreSQL is “prefer”. When QueryTree connects it will be using this default because we don’t override it in the connection string. So encryption is used if the server supports it. We could potentially add an option to enforce the use of SSL.
