### ISSUE TITLE
PostgreSQL - No Tables found

### ISSUE THREAD

**Issue by StepBee** [d4software/QueryTree#97]
Hi,

we are trying to get QueryTree running with our PostgreSQL database, but unfortunately fail with "No Tables found".
We thought #72 might have affected us, but we installed the latest docker container and in addition manually installed the latest release 3.0.99-beta, as according to the commit mentioned in #72 this should have been fixed - but without success, the error stayed the same.

We tried another smaller database of the same database server, and it worked - so the connection to the database server itself is fine.

When looking at the requests between the browser and querytree, i can see
```
Request URL: https://querytree.<mydomain.com>/api/connections/1/tables/
Request Method: GET
Status Code: 404 
```
 When capturing the transferred data between the PostgreSQL server and querytree, i can see the database is sending all tables names in its response.
I therefore think it's a bug while processing the tables in querytree.

Unfortunately, i can't see anything obvious, when setting the Default log level to "Debug" in appsettings.json.
I'm wondering where else i could search for hint or what else i could provide here, to have a second pair of eyes spot the problem?

In general during troubleshooting i felt more detailed or specific error messages would be a great hint.

Cheers,
Step

**Comment by d4nt** [comment]
@StepBee There must be something in the structure of your particular postgres database that QueryTree gets confused about, causing it to crash somewhere in `GetDbModel`. Then later when the frontend asks for the database structure info, it gets 404 in response because it hasn't been built.

You mentioned that a different database worked ok. There must be something unique to the bigger database that causes this issue.

Without having your specific database, I can't really debug it. Would you be prepared to post a link to the bigger database, or a sample database that demonstrates the issue?

**Comment by Gasprog13** [comment]
@StepBee, Hi did you manage to find a solution to this issue?

**Comment by StepBee** [comment]
@Gasprog13 we figured out, weirdly, when creating a new read-only user, instead of a superuser, we were presented with a table selection. But then problems with table caching appeared and we decided, the tool wasn't really fitting our requirements.
